### ISSUE TITLE
error al intentar ingresar a una cuenta existente 

### ISSUE THREAD

**Issue by Lofas007** [No-Country-simulation/C22-23-t-webapp#61]
Fecha: 11/12/2024.
ID bug: BUG-008.
ID del caso de prueba: CSHU-009.

Entorno:
sistema operativo: window 11.
Chrome: Versión 131.0.6778.86
Firefox: Versión 132.
microsoft edge: Versión 131.0.2903.86.

Descripcion: visualizar las barras y el contenido que se pueda ingresar en el.

Resultado esperado: se deberia poder visualizar las dos barras de ingreso y estas deberian permitir que se escriba la informacion adecuada.

Resultado obtenido: las barras se visualizan adecuadamente sin embargo el texto esta en un color ilegible de forma que no se persive nada de lo que se escriba.

Pasos:
1.ingresar al apartado "home". 
2.clickear el icono de la personita en la esquina derecha de la pagina. 
3.clickear el boton "inicial sesion".

Credenciales:
correo electronico: [mixexir644@bawsny.com](mailto:mixexir644@bawsny.com)
contraseña: Pa1234567##.

Evidencia:

https://github.com/user-attachments/assets/4c861922-baeb-40c7-a984-b579c2850501

**Comment by sosaian** [comment]
Fixed in commit `e5ff579` que se puede ver [aquí](https://github.com/No-Country-simulation/C22-23-t-webapp/commit/e5ff579bf01c835feea78cfb03b5e63d93622ed9)
