### ISSUE TITLE
Error en el almacenamiento de la informacion de los usuarios.

### ISSUE THREAD

**Issue by Lofas007** [No-Country-simulation/C22-23-t-webapp#62]
Fecha: 11/12/2024
Ambiente: Registro de usuario.
ID bug: BUG-010.
ID del caso de prueba: CSHU-010.

Entorno:
sistema operativo: window 11.
Chrome: Versión 131.0.6778.86
Firefox: Versión 132.
microsoft edge: Versión 131.0.2903.86.

Descripcion: la base de datos parece no estar bien conectada con el sitio web y la informacion de los usuarios.

Resultado esperado: los datos de los usuarios son guardados como corresponde en la base de datos, asi pudiendo ingresar a sus cuentas en cualquier momento con las credenciales que escojieron. no se deberia aceptar el registro de otra persona con las mismas credenciales

Resultado obtenido: un usuario que fue registrado anteriormente puede volver a hacer el registro con las mismas credenciales, asi asegurando que dichos datos no se estan guardando como corresponde en la base de datos.

Pasos:
1.ingresar al apartado "home".
2.clickear el icono de una personita en la esquina superior derecha.
3.clickear el boton "unirse".
4.llenar el formulario con los datos establecidos.
5.continuar con el registro y esperar la confirmacion del sitio web.
6.volver a cargar la pagina y repetir el proceso.

Credenciales:
correo electronico: [mixexir644@bawsny.com](mailto:mixexir644@bawsny.com)
contraseña: Pa1234567##.

Evidencia:

https://github.com/user-attachments/assets/44326313-3f73-4b7f-9aef-c6e057f1199d

**Comment by sosaian** [comment]
Arreglado en el commit `52955b3` que se puede ver [aquí](https://github.com/No-Country-simulation/C22-23-t-webapp/commit/52955b3038ea8a47d09cdfc6176c92733f29006c#diff-6976bebfaf3e6c346dbc20fb1c1e3b0270b706f5866e010021681f5e0c206890)
