### ISSUE TITLE
Formulario incapacitado.

### ISSUE THREAD

**Issue by Lofas007** [No-Country-simulation/C22-23-t-webapp#70]
Fecha: 12/12/2024
ID del bug: BUG-010
ID del caso de prueba: CSHU-004

Ambiente:
Sistema operativo: Windows 11
Google Chrome: Versión 131.0.6778.86
Mozilla Firefox: Versión 132
Microsoft Edge: No especificado

Descripción: El formulario de registro no permite el registro de nuevos usuarios.

Resultado esperado: Los usuarios deberían poder completar el formulario de registro de manera fácil y sin complicaciones.

Resultado obtenido: El formulario no acepta el registro de nuevos usuarios.

Pasos para reproducir:
1.Ingresar al sitio web.
2.Navegar a la sección "Empieza a adoptar" o "Buscar mascotas".
3.Hacer clic en el icono de usuario en la esquina superior derecha.
4.Hacer clic en el botón "Únete".
5.Completar y enviar el formulario de registro.

Credenciales:
Correo electrónico: mixexir644@bawsny.com
Contraseña: Pa1234567##

Evidencia:

https://github.com/user-attachments/assets/12228a60-e09e-46d1-8899-6337d467e287

**Comment by sosaian** [comment]
Técnicamente no es un bug porque no puedo verificar la base de datos en el momento que se encontró el error reportado. Agregamos el commit `46c1599` que se puede acceder [aquí](https://github.com/No-Country-simulation/C22-23-t-webapp/commit/46c1599aad311b428f679dbb86492f629d46d899) en donde agregamos un modal para mostrar un error cuando el correo ingresado ya fue registrado por otro usuario, mejorando el UX para este tipo de situaciones como el de esta issue.
