### ISSUE TITLE
Ingreso deshabilitado

### ISSUE THREAD

**Issue by Lofas007** [No-Country-simulation/C22-23-t-webapp#71]
Fecha: 12/12/2024.
ID del bug: BUG-011.
ID del caso de prueba asociado: CSHU-005.

Entorno:
sistema operativo: window 11.
Chrome: Versión 131.0.6778.86
Firefox: Versión 132.
microsoft edge: Versión 131.0.2903.86.

Descripción: el ingreso a una cuenta existente esta inhabilitado.

Resultado esperado: al rellenar los campos pertinentes en el ingreso, se deberia permitir el acceso a la cuenta.

Resultado obtenido: al intentar ingresar a la cuenta aparece un mensaje de rechazo para el ingreso.

Pasos:
1.ingresar al sitio web.
2.ir al apartado "adoptar".
3.rellenar el formulario con las credenciales dadas.

Credenciales:
correo electronico: mixexir644@bawsny.com
contraseña: Pa1234567##.

Evidencia:

![Screenshot (16)](https://github.com/user-attachments/assets/4b089e63-62be-48d5-b4af-d80dd3761907)

**Comment by sosaian** [comment]
Te aseguraste de haberte registrado nuevamente al iniciar el servidor backend de nuevo? Por cuestiones del entorno de desarrollo, cada vez que se vuelve a iniciar el backend (por ejemplo al reiniciar la computadora) es necesario volver a registrarse, idealmente con las mismas credenciales para poder replicar tu problema

**Comment by Lofas007** [comment]
Justo en ese momento estaba resolviendo los conflictos de codigo que tenia con el docker y el .env mal puesto en front. ese caso queda anulado
